@echo off
REM make-quiz-list.bat - rebuild files.txt (in THIS folder) from the .json / .cfcq.json decks here.
REM Double-click it after you add or remove a deck. (*.json catches .cfcq.json too.)
setlocal
set "dir=%~dp0"
> "%dir%files.txt" echo # Auto-generated by make-quiz-list - one deck filename per line.
>> "%dir%files.txt" echo # Re-run the script after adding or removing decks.
for /f "delims=" %%f in ('dir /b /a-d /o:n "%dir%*.json" 2^>nul') do >> "%dir%files.txt" echo %%f
echo Updated "%dir%files.txt":
type "%dir%files.txt"
endlocal
