#!/usr/bin/env sh
# make-quiz-list.sh — rebuild files.txt (in THIS folder) from the .json / .cfcq.json decks here.
# Run it after you add or remove a deck. Works in Git Bash, macOS, and Linux.
# (.cfcq.json files end in .json, so the *.json glob catches both.)

dir="$(cd "$(dirname "$0")" && pwd)"
{
  echo "# Auto-generated by make-quiz-list — one deck filename per line."
  echo "# Re-run the script after adding or removing decks."
  ( cd "$dir" && ls -1 -- *.json 2>/dev/null | sort )
} > "$dir/files.txt"

echo "Updated $dir/files.txt:"
cat "$dir/files.txt"
